name: Compile application binary

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-dev --no-progress

    - name: Set application environment to development
      run: echo "ENV=development" > .env

    - name: Build the application
      run: |
        echo "Building the application!"
        DATE=$(date '+%F')
        SHORT_SHA=$(echo 07ce6ad72d9e29c23253e30394cbb6dc6b5ac19e | cut -c1-7)
        VERSION="${DATE}-dev-master-${SHORT_SHA}"
        php hyde app:build --build-version="${VERSION}"

    - name: Calculate checksum
      run: |
        cd builds
        sha256sum hyde > checksum
        echo "SHA256 checksum of the application binary: $(cat checksum)"

    - name: Upload the application artifact
      uses: actions/upload-artifact@v3
      with:
        name: hyde
        path: builds/hyde

    - name: Upload the checksum artifact
      uses: actions/upload-artifact@v3
      with:
        name: checksum
        path: builds/checksum
