name: Compile application binary

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-dev --no-progress

    - name: Set application environment to development
      run: echo "ENV=development" > .env

    - name: Build the standalone application binary
      run: |
        echo "Building the application!"
        DATE=$(date '+%F')
        SHORT_SHA=$(echo 07ce6ad72d9e29c23253e30394cbb6dc6b5ac19e | cut -c1-7)
        VERSION="${DATE}-dev-master-${SHORT_SHA}"
        php hyde app:build --build-version="${VERSION}"

    - name: Calculate checksum
      run: |
        cd builds
        sha256sum hyde > checksum
        echo "SHA256 checksum of the application binary: $(cat checksum)"

    - name: Upload the application artifact
      uses: actions/upload-artifact@v3
      with:
        name: hyde
        path: builds/hyde

    - name: Upload the checksum artifact
      uses: actions/upload-artifact@v3
      with:
        name: checksum
        path: builds/checksum


# TODO: If the build is for a release tag we attach it to that, otherwise we create a prerelease for it

  create-prerelease:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Download the application artifact
      uses: actions/download-artifact@v3
      with:
        name: hyde
        path: builds

    - name: Download the checksum artifact
      uses: actions/download-artifact@v3
      with:
        name: checksum
        path: builds

    - name: Create version information
      run: |
        DATE=$(date '+%F')
        SHORT_SHA=$(echo 07ce6ad72d9e29c23253e30394cbb6dc6b5ac19e | cut -c1-7)
        VERSION_TAG="${DATE}-dev-master-${SHORT_SHA}"
        VERSION_NAME="${DATE} - dev-master-${SHORT_SHA}"
        echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV
        echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
        echo "CHECKSUM=$(cat builds/checksum)" >> $GITHUB_ENV

        echo "VERSION_TAG=${VERSION_TAG}"
        echo "VERSION_NAME=${VERSION_NAME}"
        echo "CHECKSUM=$(cat builds/checksum)"

    - name: Create a prerelease
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        name: ${{ env.VERSION_NAME }}
        tag: ${{ env.VERSION_TAG }}
        artifacts: builds/hyde, builds/checksum
        body: |
          SHA256 checksum of the application binary: ${{ env.CHECKSUM }}
        prerelease: true
